# Site settings
title: NCAR-RAF netCDF Conventions
description: >-
  File format conventions for airborne atmospheric research data from
  NSF NCAR Research Aviation Facility and partners.
baseurl: "/aircraft_netCDF_Conventions"
url: "https://ncar.github.io"
analytics:

# Theme
remote_theme: ncar/koru-jekyll@1.1.0

# Code highlighting
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false
  parse_block_html: true
  toc_levels: 2..3

# Plugins
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-sitemap

# SEO settings
tagline: Version 2.1 - File format conventions for airborne atmospheric research
author: NSF NCAR Research Aviation Facility

# Exclude from build
exclude:
  - .git/
  - .github/
  - README.md.backup
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
